"""initial schema

Revision ID: ba318b8f0548
Revises: 
Create Date: 2026-10-01 11:29:38.343857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba318b8f0548'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('cloud_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('AWS', 'AZURE', 'GCP', name='cloudproviderenum'), nullable=False),
    sa.Column('account_label', sa.String(length=128), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'ERROR', 'PENDING', name='accountstatusenum'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('cloud_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloud_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scanstatusenum'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_jobs_celery_task_id'), ['celery_task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scan_jobs_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_status'), ['status'], unique=False)

    op.create_table('cloud_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('AWS', 'AZURE', 'GCP', name='cloudproviderenum'), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('bucket_name', sa.String(length=256), nullable=True),
    sa.Column('storage_class', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('object_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cloud_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cloud_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloud_metrics_cloud_account_id'), ['cloud_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_metrics_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_metrics_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('lines_scanned', sa.Integer(), nullable=False),
    sa.Column('scan_duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.Enum('SECRET', 'CODE_PATTERN', 'DEPENDENCY', 'MISCONFIGURATION', name='findingtypeenum'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severityenum'), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('matched_text', sa.Text(), nullable=True),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('package_name', sa.String(length=128), nullable=True),
    sa.Column('package_version', sa.String(length=64), nullable=True),
    sa.Column('fix_version', sa.String(length=64), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_severity'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_job_id'))

    op.drop_table('vulnerabilities')
    op.drop_table('scan_results')
    with op.batch_alter_table('cloud_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_metrics_provider'))
        batch_op.drop_index(batch_op.f('ix_cloud_metrics_collected_at'))
        batch_op.drop_index(batch_op.f('ix_cloud_metrics_cloud_account_id'))

    op.drop_table('cloud_metrics')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_requested_by'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_celery_task_id'))

    op.drop_table('scan_jobs')
    with op.batch_alter_table('cloud_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_accounts_user_id'))

    op.drop_table('cloud_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
